name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-macos:
    name: Swift ${{ matrix.swift }} on Xcode ${{ matrix.xcode }}
    runs-on: ${{ matrix.runs-on }}
    env:
      DEVELOPER_DIR: "/Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer"
    strategy:
      fail-fast: false
      matrix:
        include:
          - swift: "6.0"
            xcode: "16.0"
            runs-on: macos-15
          - swift: "6.1"
            xcode: "16.3"
            runs-on: macos-15
          - swift: "6.2"
            xcode: "26.0"
            runs-on: macos-26
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5

      - name: Show Swift version
        run: swift --version

      - name: Lint
        run: swift format lint --strict --recursive .

      - name: Build
        run: swift build -v

      - name: Test
        run: swift test -v

  test-linux:
    name: Swift ${{ matrix.swift-version }} on Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        swift-version:
          - 6.0.3
          - 6.1.3
          - 6.2.1
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Swift
        uses: vapor/swiftly-action@v0.2
        with:
          toolchain: ${{ matrix.swift-version }}

      - name: Build
        run: swift build -v

      - name: Test
        run: swift test -v
